version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smart-fit-postgres
    environment:
      POSTGRES_DB: smart_fit_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-fit-network

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: smart-fit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-fit-network

  # Smart-Fit-Agent Application
  app:
    build: .
    container_name: smart-fit-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-postgres123}@postgres:5432/smart_fit_agent
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - smart-fit-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  smart-fit-network:
    driver: bridge
